// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// add
int add(int x, int y, int z);
RcppExport SEXP _anpan_add(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(add(x, y, z));
    return rcpp_result_gen;
END_RCPP
}
// l2p
double l2p();
RcppExport SEXP _anpan_l2p() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(l2p());
    return rcpp_result_gen;
END_RCPP
}
// llij_gauss
NumericVector llij_gauss(NumericVector m1, NumericVector s1, NumericVector l, NumericVector yj, NumericVector s2);
RcppExport SEXP _anpan_llij_gauss(SEXP m1SEXP, SEXP s1SEXP, SEXP lSEXP, SEXP yjSEXP, SEXP s2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type l(lSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type yj(yjSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s2(s2SEXP);
    rcpp_result_gen = Rcpp::wrap(llij_gauss(m1, s1, l, yj, s2));
    return rcpp_result_gen;
END_RCPP
}
// get_s12x22inv
List get_s12x22inv(NumericMatrix x);
RcppExport SEXP _anpan_get_s12x22inv(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(get_s12x22inv(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_anpan_add", (DL_FUNC) &_anpan_add, 3},
    {"_anpan_l2p", (DL_FUNC) &_anpan_l2p, 0},
    {"_anpan_llij_gauss", (DL_FUNC) &_anpan_llij_gauss, 5},
    {"_anpan_get_s12x22inv", (DL_FUNC) &_anpan_get_s12x22inv, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_anpan(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
