// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// arma_exp
arma::mat arma_exp(arma::mat m);
RcppExport SEXP _anpan_arma_exp(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(arma_exp(m));
    return rcpp_result_gen;
END_RCPP
}
// arma_solve
arma::mat arma_solve(arma::mat m);
RcppExport SEXP _anpan_arma_solve(SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(arma_solve(m));
    return rcpp_result_gen;
END_RCPP
}
// s22_inv
arma::mat s22_inv(arma::mat& cor_mat, arma::uword j);
RcppExport SEXP _anpan_s22_inv(SEXP cor_matSEXP, SEXP jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type cor_mat(cor_matSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type j(jSEXP);
    rcpp_result_gen = Rcpp::wrap(s22_inv(cor_mat, j));
    return rcpp_result_gen;
END_RCPP
}
// woodbury_s22_inv
arma::mat woodbury_s22_inv(arma::mat& cor_mat_inv, arma::mat& cor_mat, arma::uword j, arma::uvec& o2, arma::uvec& jmj);
RcppExport SEXP _anpan_woodbury_s22_inv(SEXP cor_mat_invSEXP, SEXP cor_matSEXP, SEXP jSEXP, SEXP o2SEXP, SEXP jmjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type cor_mat_inv(cor_mat_invSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type cor_mat(cor_matSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type j(jSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type o2(o2SEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type jmj(jmjSEXP);
    rcpp_result_gen = Rcpp::wrap(woodbury_s22_inv(cor_mat_inv, cor_mat, j, o2, jmj));
    return rcpp_result_gen;
END_RCPP
}
// precompute_arr
List precompute_arr(arma::uword j, arma::mat& cor_mat, arma::mat& cor_mat_inv);
RcppExport SEXP _anpan_precompute_arr(SEXP jSEXP, SEXP cor_matSEXP, SEXP cor_mat_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uword >::type j(jSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type cor_mat(cor_matSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type cor_mat_inv(cor_mat_invSEXP);
    rcpp_result_gen = Rcpp::wrap(precompute_arr(j, cor_mat, cor_mat_inv));
    return rcpp_result_gen;
END_RCPP
}
// inv_logit
arma::vec inv_logit(arma::vec x);
RcppExport SEXP _anpan_inv_logit(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(inv_logit(x));
    return rcpp_result_gen;
END_RCPP
}
// vec_integrand_logistic
arma::vec vec_integrand_logistic(arma::vec phylo_effect_vec, double mu_bar_j, double sigma_bar_j, double yj, double lm_term, double offset_term, double sqrt2pi, int log_out);
RcppExport SEXP _anpan_vec_integrand_logistic(SEXP phylo_effect_vecSEXP, SEXP mu_bar_jSEXP, SEXP sigma_bar_jSEXP, SEXP yjSEXP, SEXP lm_termSEXP, SEXP offset_termSEXP, SEXP sqrt2piSEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type phylo_effect_vec(phylo_effect_vecSEXP);
    Rcpp::traits::input_parameter< double >::type mu_bar_j(mu_bar_jSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_bar_j(sigma_bar_jSEXP);
    Rcpp::traits::input_parameter< double >::type yj(yjSEXP);
    Rcpp::traits::input_parameter< double >::type lm_term(lm_termSEXP);
    Rcpp::traits::input_parameter< double >::type offset_term(offset_termSEXP);
    Rcpp::traits::input_parameter< double >::type sqrt2pi(sqrt2piSEXP);
    Rcpp::traits::input_parameter< int >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(vec_integrand_logistic(phylo_effect_vec, mu_bar_j, sigma_bar_j, yj, lm_term, offset_term, sqrt2pi, log_out));
    return rcpp_result_gen;
END_RCPP
}
// integrand_logistic
double integrand_logistic(double phylo_effect, double mu_bar_j, double sigma_bar_j, double yj, double lm_term, double offset_term, double sqrt2pi, int log_out);
RcppExport SEXP _anpan_integrand_logistic(SEXP phylo_effectSEXP, SEXP mu_bar_jSEXP, SEXP sigma_bar_jSEXP, SEXP yjSEXP, SEXP lm_termSEXP, SEXP offset_termSEXP, SEXP sqrt2piSEXP, SEXP log_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type phylo_effect(phylo_effectSEXP);
    Rcpp::traits::input_parameter< double >::type mu_bar_j(mu_bar_jSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_bar_j(sigma_bar_jSEXP);
    Rcpp::traits::input_parameter< double >::type yj(yjSEXP);
    Rcpp::traits::input_parameter< double >::type lm_term(lm_termSEXP);
    Rcpp::traits::input_parameter< double >::type offset_term(offset_termSEXP);
    Rcpp::traits::input_parameter< double >::type sqrt2pi(sqrt2piSEXP);
    Rcpp::traits::input_parameter< int >::type log_out(log_outSEXP);
    rcpp_result_gen = Rcpp::wrap(integrand_logistic(phylo_effect, mu_bar_j, sigma_bar_j, yj, lm_term, offset_term, sqrt2pi, log_out));
    return rcpp_result_gen;
END_RCPP
}
// bintegrate_finite
NumericVector bintegrate_finite(double mu_bar_j, double sigma_bar_j, double yj, double lmj, double offset_j, double rt2pi, double lower, double upper);
RcppExport SEXP _anpan_bintegrate_finite(SEXP mu_bar_jSEXP, SEXP sigma_bar_jSEXP, SEXP yjSEXP, SEXP lmjSEXP, SEXP offset_jSEXP, SEXP rt2piSEXP, SEXP lowerSEXP, SEXP upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type mu_bar_j(mu_bar_jSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_bar_j(sigma_bar_jSEXP);
    Rcpp::traits::input_parameter< double >::type yj(yjSEXP);
    Rcpp::traits::input_parameter< double >::type lmj(lmjSEXP);
    Rcpp::traits::input_parameter< double >::type offset_j(offset_jSEXP);
    Rcpp::traits::input_parameter< double >::type rt2pi(rt2piSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    rcpp_result_gen = Rcpp::wrap(bintegrate_finite(mu_bar_j, sigma_bar_j, yj, lmj, offset_j, rt2pi, lower, upper));
    return rcpp_result_gen;
END_RCPP
}
// bintegrate_infinite
NumericVector bintegrate_infinite(double mu_bar_j, double sigma_bar_j, double yj, double lmj, double offset_j, double rt2pi);
RcppExport SEXP _anpan_bintegrate_infinite(SEXP mu_bar_jSEXP, SEXP sigma_bar_jSEXP, SEXP yjSEXP, SEXP lmjSEXP, SEXP offset_jSEXP, SEXP rt2piSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type mu_bar_j(mu_bar_jSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_bar_j(sigma_bar_jSEXP);
    Rcpp::traits::input_parameter< double >::type yj(yjSEXP);
    Rcpp::traits::input_parameter< double >::type lmj(lmjSEXP);
    Rcpp::traits::input_parameter< double >::type offset_j(offset_jSEXP);
    Rcpp::traits::input_parameter< double >::type rt2pi(rt2piSEXP);
    rcpp_result_gen = Rcpp::wrap(bintegrate_infinite(mu_bar_j, sigma_bar_j, yj, lmj, offset_j, rt2pi));
    return rcpp_result_gen;
END_RCPP
}
// llij_binom
arma::vec llij_binom(arma::vec lm_mean, arma::mat sigma_inv_mat, arma::mat cor21_mat, double sigma_phylo, arma::vec phylo_effects, arma::vec Y, arma::vec effect_means, double rt2pi);
RcppExport SEXP _anpan_llij_binom(SEXP lm_meanSEXP, SEXP sigma_inv_matSEXP, SEXP cor21_matSEXP, SEXP sigma_phyloSEXP, SEXP phylo_effectsSEXP, SEXP YSEXP, SEXP effect_meansSEXP, SEXP rt2piSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type lm_mean(lm_meanSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma_inv_mat(sigma_inv_matSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cor21_mat(cor21_matSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_phylo(sigma_phyloSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phylo_effects(phylo_effectsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type effect_means(effect_meansSEXP);
    Rcpp::traits::input_parameter< double >::type rt2pi(rt2piSEXP);
    rcpp_result_gen = Rcpp::wrap(llij_binom(lm_mean, sigma_inv_mat, cor21_mat, sigma_phylo, phylo_effects, Y, effect_means, rt2pi));
    return rcpp_result_gen;
END_RCPP
}
// llij_gauss_eval
arma::vec llij_gauss_eval(arma::vec m1, arma::vec s1, arma::vec l, arma::vec yj, double s2);
RcppExport SEXP _anpan_llij_gauss_eval(SEXP m1SEXP, SEXP s1SEXP, SEXP lSEXP, SEXP yjSEXP, SEXP s2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type l(lSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yj(yjSEXP);
    Rcpp::traits::input_parameter< double >::type s2(s2SEXP);
    rcpp_result_gen = Rcpp::wrap(llij_gauss_eval(m1, s1, l, yj, s2));
    return rcpp_result_gen;
END_RCPP
}
// llij_gauss
arma::vec llij_gauss(int p, arma::vec lm_means, arma::mat sigma_inv, double sigma_phylo, arma::mat cor_arr, arma::vec phylo_effects, double sigma_resid, arma::vec Y);
RcppExport SEXP _anpan_llij_gauss(SEXP pSEXP, SEXP lm_meansSEXP, SEXP sigma_invSEXP, SEXP sigma_phyloSEXP, SEXP cor_arrSEXP, SEXP phylo_effectsSEXP, SEXP sigma_residSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lm_means(lm_meansSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma_inv(sigma_invSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_phylo(sigma_phyloSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cor_arr(cor_arrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phylo_effects(phylo_effectsSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_resid(sigma_residSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(llij_gauss(p, lm_means, sigma_inv, sigma_phylo, cor_arr, phylo_effects, sigma_resid, Y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_anpan_arma_exp", (DL_FUNC) &_anpan_arma_exp, 1},
    {"_anpan_arma_solve", (DL_FUNC) &_anpan_arma_solve, 1},
    {"_anpan_s22_inv", (DL_FUNC) &_anpan_s22_inv, 2},
    {"_anpan_woodbury_s22_inv", (DL_FUNC) &_anpan_woodbury_s22_inv, 5},
    {"_anpan_precompute_arr", (DL_FUNC) &_anpan_precompute_arr, 3},
    {"_anpan_inv_logit", (DL_FUNC) &_anpan_inv_logit, 1},
    {"_anpan_vec_integrand_logistic", (DL_FUNC) &_anpan_vec_integrand_logistic, 8},
    {"_anpan_integrand_logistic", (DL_FUNC) &_anpan_integrand_logistic, 8},
    {"_anpan_bintegrate_finite", (DL_FUNC) &_anpan_bintegrate_finite, 8},
    {"_anpan_bintegrate_infinite", (DL_FUNC) &_anpan_bintegrate_infinite, 6},
    {"_anpan_llij_binom", (DL_FUNC) &_anpan_llij_binom, 8},
    {"_anpan_llij_gauss_eval", (DL_FUNC) &_anpan_llij_gauss_eval, 5},
    {"_anpan_llij_gauss", (DL_FUNC) &_anpan_llij_gauss, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_anpan(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
