#' Estimate a species-pathway abundance random effects model
#' @description Fit a model of the form pwy_abd ~ species_abd + (1|pwy) + (0+group|pwy) for a single
#'   bug
#' @details The priors are as follows: A) student_t(3, mean(pwy_abd), 2.5) on the intercept at the
#'   mean species abundance. B) half student_t(3, 0, 2.5) on the residual noise C) 0-centered normal
#'   priors on pathway specific effects C1) half student_t(5,0,2.5) on the SD of pathway intercepts
#'   C2) half standard normal on the SD of group-specific effects.
#'
#'   The pathway index is generated by converting the pwy column to a factor and then to the
#'   corresponding integer index.
#'
#'   The group_ind column should be numeric with values in {0,1}
#'
#'   The main parameter of interest is the \code{pwy_effects} vector. When
#' @param bug_pwy_dat a data frame with a row for each observation and columns "pwy",
#'   "log10_species_abd", "log10_pwy_abd", and a group indicator column named according to the
#'   \code{group_ind} argument
#' @param group_ind a character giving the name of the column for the 0/1 group indicator variable
#'   in \code{bug_pwy_dat}
#' @param ... other arguments to pass to cmdstanr::sample()
#' @returns a list containing the CmdStanMCMC object of the model fit and the pwy-index map
#' @seealso [cmdstanr::CmdStanMCMC()]
#' @export
anpan_pwy_ranef = function(bug_pwy_dat,
                           group_ind = "crc",
                           ...) {

  if (!all(c("pwy", "log10_species_abd", "log10_pwy_abd", group_ind) %in% names(bug_pwy_dat))) {
    stop("The necessary variables are not present in bug_pwy_dat. See ?anpan_pwy_ranef for what the columns should be called.")
  }

  if (!is.factor(bug_pwy_dat$pwy)) {
    warning("Converting the pwy column to a factor.")
  }

  model_path = system.file("stan", "pwy_ranef.stan",
                           package = 'anpan',
                           mustWork = TRUE)

  pwy_ranef_model = cmdstanr::cmdstan_model(stan_file = model_path,
                                            quiet = TRUE)

  data_list = list(N = nrow(bug_pwy_dat),
                   pwy_abd = bug_pwy_dat$log10_pwy_abd,
                   pwy_mean = mean(bug_pwy_dat$log10_pwy_abd),
                   intercept_species = model.matrix(~log10_species_abd, data = bug_pwy_dat),
                   N_pwy = dplyr::n_distinct(bug_pwy_dat$pwy),
                   pwy_ind = as.integer(factor(bug_pwy_dat$pwy)),
                   group_ind = bug_pwy_dat[[group_ind]])

  pwy_ind_map = tibble(index = 1:data_list$N_pwy,
                       variable = paste("pwy_effects[", index, "]", sep = ""),
                       pwy = levels(factor(bug_pwy_dat$pwy)))

  mod_fit = pwy_ranef_model$sample(data = data_list, ...)

  return(tibble(model_fit = list(mod_fit), pwy_index_map = list(pwy_ind_map)))
}

#' Fit the pathway random effects model for multiple bugs
#' @details In addition to the column requirements of \code{anpan_pwy_ranef()}, the input data frame
#'   \code{bug_pwy_dat} here must also contain a variable called "bug" which gives a unique
#'   identifier for each bug.
#' @returns a tibble of row-binded anpan_pwy_ranef results
#' @inheritParams anpan_pwy_ranef
#' @export
anpan_pwy_ranef_batch = function(bug_pwy_dat,
                                 group_ind = "crc", ...) {

  if (!all(c("bug", "pwy", "log10_species_abd", "log10_pwy_abd", group_ind) %in% names(bug_pwy_dat))) {
    stop("The necessary variables are not present in bug_pwy_dat. See ?anpan_pwy_ranef for what the columns should be called.")
  }

  model_path = system.file("stan", "pwy_ranef.stan",
                           package = 'anpan',
                           mustWork = TRUE)

  # Compile it once ahead of time
  pwy_ranef_model = cmdstanr::cmdstan_model(stan_file = model_path,
                                            quiet = TRUE)

  p = progressr::progressor(steps = dplyr::n_distinct(bug_pwy_dat$bug))

  res = bug_pwy_dat |>
    dplyr::group_split(bug) |>
    furrr::future_map_dfr(function(.x) {bug_res = anpan_pwy_ranef(bug_pwy_dat = .x,
                                                                  group_ind = group_ind,
                                                                  ...)
                                        p()
                                        return(bug_res)},
                          .options = furrr::furrr_options(seed = 123))

  return(res)
}
