# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

llij_gauss_inputs <- function(p, lm_means, sigma_inv, sigma_phylo, cor_arr, phylo_effects, sigma_resid, Y, cov_mat_diag) {
    .Call(`_anpan_llij_gauss_inputs`, p, lm_means, sigma_inv, sigma_phylo, cor_arr, phylo_effects, sigma_resid, Y, cov_mat_diag)
}

llij_gauss_eval <- function(m1, s1, l, yj, s2) {
    .Call(`_anpan_llij_gauss_eval`, m1, s1, l, yj, s2)
}

get_s12x22inv <- function(x) {
    .Call(`_anpan_get_s12x22inv`, x)
}

llij_gauss <- function(p, lm_means, sigma_inv, sigma_phylo, cor_arr, phylo_effects, sigma_resid, Y, cov_mat_diag) {
    .Call(`_anpan_llij_gauss`, p, lm_means, sigma_inv, sigma_phylo, cor_arr, phylo_effects, sigma_resid, Y, cov_mat_diag)
}

