# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

arma_exp <- function(m) {
    .Call(`_anpan_arma_exp`, m)
}

inv_logit <- function(x) {
    .Call(`_anpan_inv_logit`, x)
}

vec_integrand_logistic <- function(phylo_effect_vec, mu_bar_j, sigma_bar_j, yj, lm_term, offset_term, sqrt2pi, log_out) {
    .Call(`_anpan_vec_integrand_logistic`, phylo_effect_vec, mu_bar_j, sigma_bar_j, yj, lm_term, offset_term, sqrt2pi, log_out)
}

integrand_logistic <- function(phylo_effect, mu_bar_j, sigma_bar_j, yj, lm_term, offset_term, sqrt2pi, log_out) {
    .Call(`_anpan_integrand_logistic`, phylo_effect, mu_bar_j, sigma_bar_j, yj, lm_term, offset_term, sqrt2pi, log_out)
}

bintegrate_finite <- function(mu_bar_j, sigma_bar_j, yj, lmj, offset_j, rt2pi, lower, upper) {
    .Call(`_anpan_bintegrate_finite`, mu_bar_j, sigma_bar_j, yj, lmj, offset_j, rt2pi, lower, upper)
}

bintegrate_infinite <- function(mu_bar_j, sigma_bar_j, yj, lmj, offset_j, rt2pi) {
    .Call(`_anpan_bintegrate_infinite`, mu_bar_j, sigma_bar_j, yj, lmj, offset_j, rt2pi)
}

llij_binom <- function(lm_mean, sigma_inv_mat, cor21_mat, sigma_phylo, phylo_effects, Y, effect_means, rt2pi) {
    .Call(`_anpan_llij_binom`, lm_mean, sigma_inv_mat, cor21_mat, sigma_phylo, phylo_effects, Y, effect_means, rt2pi)
}

llij_gauss_eval <- function(m1, s1, l, yj, s2) {
    .Call(`_anpan_llij_gauss_eval`, m1, s1, l, yj, s2)
}

llij_gauss <- function(p, lm_means, sigma_inv, sigma_phylo, cor_arr, phylo_effects, sigma_resid, Y) {
    .Call(`_anpan_llij_gauss`, p, lm_means, sigma_inv, sigma_phylo, cor_arr, phylo_effects, sigma_resid, Y)
}

